name: weather
description: "Weather app for KM/TMAP on UPOL."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.67.0
  shortuid: ^1.0.0
  uuid: 3.0.7
  rename_app: ^1.3.2
  step_progress_indicator: ^1.0.2
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  weather_icons: ^3.0.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  blurrycontainer: ^1.0.2
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  community_charts_flutter: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/wmo_codes_descriptions.json
    - assets/sunset_icon.svg
    - assets/sunrise_icon.svg

flutter_native_splash:
  color: "#006FAD"
  background_image: "assets/splash_icon.png"
  android_12:
    color: "#006FAD"
    icon_background_color: "#006FAD"
