name: weather
description: "Weather app for KM/TMAP on UPOL."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  community_charts_flutter: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/wmo_codes_descriptions.json

flutter_native_splash:
  color: "#006FAD"
  background_image: "assets/splash_icon.png"
